### ISSUE TITLE
Update README.md with some building/usage steps

### ISSUE THREAD

**Issue by marcin-kozinski** [JakeWharton/diffuse#69]
Hey, do you mind if I send a simple PR updating README.md to have any usage steps at all? I would just list what worked for me, that should be easier than everyone figuring it out on their own.

**Comment by rahulsainani** [comment]
@marcin-kozinski It would be really helpful if you could do that, if you already have some usage document written, could you share here as well please or as a gist? Would help me get started.

**Comment by marcin-kozinski** [comment]
@rahulsainani You can find the steps I used in #70

**Comment by rahulsainani** [comment]
Great thank you!
