### ISSUE TITLE
Usage Difficulty

### ISSUE THREAD

**Issue by Mastersam07** [JakeWharton/diffuse#71]
I am finding it hard to set up and use the diffuse tool. After cloning this repo what next? What if I want to call the tool with GitHub actions?

**Comment by Mastersam07** [comment]
Also, it seems the project uses Gradle-5.5.1. Why not upgrade to 5.6 or later?

**Comment by Mastersam07** [comment]
I am using windows. I cloned the repo, open my command line in the project root and ran `gradlew assemble`.  The diffuse file was generated in diffuse/build/diffuse and I added it to path. Runnning the command `diffuse diff old.apk new.apk` returns the error 'diffuse' is not recognized as an internal or external command, operable program or batch file.

Any workaround?

**Comment by Mastersam07** [comment]
Renaming the diffuse file to diffuse.exe, I get the error `This version of C:\Users\USER\Desktop\COURSES\diffuse\diffuse\build\diffuse.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher`.

**Comment by ckesc** [comment]
@Mastersam07 It's not windows build. You can run program as any java jar
`java -jar diffuse/build/libs/diffuse-0.1.0-SNAPSHOT-fat.jar`

Also, looks like the program is in early stage that's why there's no prebuilt binaries yet and you should build sources by yourself.

**Comment by Mastersam07** [comment]
Understandable. I have been able to use diffuse via Github actions. It fits my use case.

**Comment by Mastersam07** [comment]
Will be closing this issue now.
