### ISSUE TITLE
Single APK/AAB analysis

### ISSUE THREAD

**Issue by fajarnuha** [JakeWharton/diffuse#75]
so far diffuse only has diff command which requires two binaries, in some usecase, we might want to just see whats the number in a binary, save it to database, and analyze the differences through some graph/trend. 

is it possible to just seeing an APK's stats instead of diffing?

**Comment by JakeWharton** [comment]
Sure. Good idea.

**Comment by JakeWharton** [comment]
Started in 6de9b44537a2e995752b4ec7aa0989569c55c63f. Lots still to do.

**Comment by JakeWharton** [comment]
This is in
