### ISSUE TITLE
Diffuse executable not changed after a change in the source code

### ISSUE THREAD

**Issue by maciejwitowski** [JakeWharton/diffuse#76]
In this scenario:
1. Run `./gradlew assemble`.
2. Change something in the source code.
3. Run `./gradlew assemble`

I don't see the change from step 2. being reflected after step 3.
 
Am I missing something or should the sources be set as input in `fatTranslationsJarProvider` task in `build.gradle`?

```
task.inputs.files(sourceSets.main.output.classesDirs)
```

**Comment by JakeWharton** [comment]
Yeah I noticed this too. You have to do a clean build. I never got around to fixing the task inputs. Would take a PR if you're up for it.

**Comment by maciejwitowski** [comment]
Sure, will do.
