### ISSUE TITLE
Bad Formatting with Bash?

### ISSUE THREAD

**Issue by recheej** [JakeWharton/diffuse#79]
I tried running diffuse with git bash and got some weird formatting. Instead of lines I see a bunch of question marks.

![image](https://user-images.githubusercontent.com/2354885/91219280-3466ea00-e6cf-11ea-806c-d643972843a3.png)

**Comment by JakeWharton** [comment]
Your screenshot is of notepad. Do the boxes show up correctly in the terminal?

This is a problem with your terminal's configuration as it does not support unicode characters which are used for the table.

**Comment by kirkaDev** [comment]
I have the same problem with git-bash.exe on Windows, but with git-cmd.exe everything is ok.

![diffuse_error](https://github.com/JakeWharton/diffuse/assets/8686389/735a5e9f-4e14-4b92-a469-cdc2abe96d3b)


![diffuse_ok](https://github.com/JakeWharton/diffuse/assets/8686389/895a76be-2fd4-487b-96ab-7161a7c41f36)
